# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rstorage.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\t\")\n\x06Volume\x12\x11\n\x02ID\x18\x01 \x01(\x0b\x32\x05.UUID\x12\x0c\n\x04size\x18\x02 \x01(\x03\"`\n\x08Response\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.Response.RequestStatus\"+\n\rRequestStatus\x12\x0e\n\nSUCCESSFUL\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"&\n\nVolumeList\x12\x18\n\x07volumes\x18\x01 \x03(\x0b\x32\x07.Volume2v\n\x07Storage\x12\x1e\n\x06\x43reate\x12\x07.Volume\x1a\t.Response\"\x00\x12\x1c\n\x06Remove\x12\x05.UUID\x1a\t.Response\"\x00\x12-\n\x04List\x12\x16.google.protobuf.Empty\x1a\x0b.VolumeList\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_RESPONSE_REQUESTSTATUS = _descriptor.EnumDescriptor(
  name='RequestStatus',
  full_name='Response.RequestStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESSFUL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=165,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_REQUESTSTATUS)


_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='UUID.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=67,
)


_VOLUME = _descriptor.Descriptor(
  name='Volume',
  full_name='Volume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Volume.ID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Volume.size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=110,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_REQUESTSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=208,
)


_VOLUMELIST = _descriptor.Descriptor(
  name='VolumeList',
  full_name='VolumeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volumes', full_name='VolumeList.volumes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=248,
)

_VOLUME.fields_by_name['ID'].message_type = _UUID
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_REQUESTSTATUS
_RESPONSE_REQUESTSTATUS.containing_type = _RESPONSE
_VOLUMELIST.fields_by_name['volumes'].message_type = _VOLUME
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['Volume'] = _VOLUME
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['VolumeList'] = _VOLUMELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:UUID)
  })
_sym_db.RegisterMessage(UUID)

Volume = _reflection.GeneratedProtocolMessageType('Volume', (_message.Message,), {
  'DESCRIPTOR' : _VOLUME,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:Volume)
  })
_sym_db.RegisterMessage(Volume)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

VolumeList = _reflection.GeneratedProtocolMessageType('VolumeList', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMELIST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:VolumeList)
  })
_sym_db.RegisterMessage(VolumeList)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=250,
  serialized_end=368,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Storage.Create',
    index=0,
    containing_service=None,
    input_type=_VOLUME,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='Storage.Remove',
    index=1,
    containing_service=None,
    input_type=_UUID,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='Storage.List',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_VOLUMELIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
